JRDB3DTraj
data
Traceback (most recent call last):
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/datasets/_base_dataset.py", line 174, in _load_simple_text_file
    fp = open(file)
FileNotFoundError: [Errno 2] No such file or directory: '../data_trajectory/test/label_02/0000.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 193, in eval_sequence
    raw_data = dataset.get_raw_seq_data(tracker, seq, is_3d)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/datasets/_base_dataset.py", line 92, in get_raw_seq_data
    raw_gt_data = self._load_raw_file(tracker, seq, is_gt=True)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/datasets/jrdb_3d_traj.py", line 166, in _load_raw_file
    read_data, ignore_data = self._load_simple_text_file(file, time_col=0, id_col=1, remove_negative_ids=True,
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/datasets/_base_dataset.py", line 248, in _load_simple_text_file
    raise TrackEvalException(
trackeval.utils.TrackEvalException: File 0000.txt cannot be read because it is either not present or invalidly formatted





JRDB3DTraj
data
Traceback (most recent call last):
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 193, in eval_sequence
    raw_data = dataset.get_raw_seq_data(tracker, seq, is_3d)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/datasets/_base_dataset.py", line 92, in get_raw_seq_data
    raw_gt_data = self._load_raw_file(tracker, seq, is_gt=True)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/datasets/jrdb_3d_traj.py", line 188, in _load_raw_file
    raise TrackEvalException(
trackeval.utils.TrackEvalException: Ground-truth data contains the following invalid timesteps in seq 0000: 1079, , 1080, , 1081, , 1082, , 1083, , 1084, , 1085, , 1086, , 1087, , 1088, , 1089, , 1090, , 1091, , 1092, , 1093, , 1094, , 1095, , 1096, , 1097, , 1098, , 1099, , 1100, , 1101, , 1102, , 1103, , 1104, , 1105, , 1106, , 1107, , 1108, , 1109, , 1110, , 1111, , 1112, , 1113, , 1114, , 1115, , 1116, , 1117, , 1118, , 1119, , 1120, , 1121, , 1122, , 1123, , 1124, , 1125, , 1126, , 1127, , 1128, , 1129, , 1130, , 1131, , 1132, , 1133, , 1134, , 1135, , 1136, , 1137, , 1138, , 1139, , 1140, , 1141, , 1142, , 1143, , 1144, , 1145, , 1146, , 1147, , 1148, , 1149, , 1150, , 1151, , 1152, , 1153, , 1154, 





JRDB3DTraj
data
Traceback (most recent call last):
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 193, in eval_sequence
    raw_data = dataset.get_raw_seq_data(tracker, seq, is_3d)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/datasets/_base_dataset.py", line 92, in get_raw_seq_data
    raw_gt_data = self._load_raw_file(tracker, seq, is_gt=True)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/datasets/jrdb_3d_traj.py", line 188, in _load_raw_file
    raise TrackEvalException(
trackeval.utils.TrackEvalException: Ground-truth data contains the following invalid timesteps in seq 0000: 1154, 





JRDB3DTraj
data
Traceback (most recent call last):
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 193, in eval_sequence
    raw_data = dataset.get_raw_seq_data(tracker, seq, is_3d)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/datasets/_base_dataset.py", line 102, in get_raw_seq_data
    ious = self._calculate_similarities(gt_dets_t, tracker_dets_t)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/datasets/jrdb_3d_traj.py", line 406, in _calculate_similarities
    raise NotImplementedError
NotImplementedError





JRDB3DTraj
data
Traceback (most recent call last):
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 193, in eval_sequence
    raw_data = dataset.get_raw_seq_data(tracker, seq, is_3d)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/datasets/_base_dataset.py", line 102, in get_raw_seq_data
    ious = self._calculate_similarities(gt_dets_t, tracker_dets_t)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/datasets/jrdb_3d_traj.py", line 403, in _calculate_similarities
    similarity_scores = self._calculate_traj_distance_3d(gt_dets_t, tracker_dets_t)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/datasets/_base_dataset.py", line 384, in _calculate_traj_distance_3d
    assert objs.shape[1] == 5
AssertionError





JRDB3DTraj
data
Traceback (most recent call last):
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 193, in eval_sequence
    raw_data = dataset.get_raw_seq_data(tracker, seq, is_3d)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/datasets/_base_dataset.py", line 102, in get_raw_seq_data
    ious = self._calculate_similarities(gt_dets_t, tracker_dets_t)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/datasets/jrdb_3d_traj.py", line 404, in _calculate_similarities
    similarity_fde_scores = self._calculate_traj_distance_final_3d(gt_dets_t, tracker_dets_t)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/datasets/_base_dataset.py", line 404, in _calculate_traj_distance_final_3d
    assert objs.shape[1] == 5
AssertionError





JRDB3DTraj
data
Traceback (most recent call last):
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 193, in eval_sequence
    raw_data = dataset.get_raw_seq_data(tracker, seq, is_3d)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/datasets/_base_dataset.py", line 102, in get_raw_seq_data
    ious = self._calculate_similarities(gt_dets_t, tracker_dets_t)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/datasets/jrdb_3d_traj.py", line 404, in _calculate_similarities
    similarity_fde_scores = self._calculate_traj_distance_final_3d(gt_dets_t, tracker_dets_t)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/datasets/_base_dataset.py", line 410, in _calculate_traj_distance_final_3d
    dist = np.sqrt((objs[o][0][-1]-hyps[h][0][-1])**2+(objs[o][1][-1]-hyps[h][1][-1])**2)
IndexError: invalid index to scalar variable.





JRDB3DTraj
data
Traceback (most recent call last):
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 193, in eval_sequence
    raw_data = dataset.get_raw_seq_data(tracker, seq, is_3d)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/datasets/_base_dataset.py", line 92, in get_raw_seq_data
    raw_gt_data = self._load_raw_file(tracker, seq, is_gt=True)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/datasets/jrdb_3d_traj.py", line 188, in _load_raw_file
    raise TrackEvalException(
trackeval.utils.TrackEvalException: Ground-truth data contains the following invalid timesteps in seq 0001: 715, , 716, , 717, , 718, , 719, , 720, , 721, , 722, , 723, , 724, , 725, , 726, , 727, , 728, , 729, , 730, , 731, , 732, , 733, , 734, , 735, , 736, , 737, , 738, , 739, , 740, , 741, , 742, , 743, , 744, , 745, , 746, , 747, , 748, , 749, , 750, , 751, , 752, , 753, , 754, , 755, , 756, , 757, , 758, , 759, , 760, , 761, , 762, , 763, , 764, , 765, , 766, , 767, , 768, , 769, , 770, , 771, , 772, , 773, , 774, , 775, , 776, , 777, , 778, , 779, , 780, , 781, , 782, , 783, , 784, , 785, , 786, , 787, , 788, , 789, , 790, 





JRDB3DTraj
data
Traceback (most recent call last):
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 193, in eval_sequence
    raw_data = dataset.get_raw_seq_data(tracker, seq, is_3d)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/datasets/_base_dataset.py", line 92, in get_raw_seq_data
    raw_gt_data = self._load_raw_file(tracker, seq, is_gt=True)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/datasets/jrdb_3d_traj.py", line 188, in _load_raw_file
    raise TrackEvalException(
trackeval.utils.TrackEvalException: Ground-truth data contains the following invalid timesteps in seq 0002: 789, , 790, , 791, , 792, , 793, , 794, , 795, , 796, , 797, , 798, , 799, , 800, , 801, , 802, , 803, , 804, , 805, , 806, , 807, , 808, , 809, , 810, , 811, , 812, , 813, , 814, , 815, , 816, , 817, , 818, , 819, , 820, , 821, , 822, , 823, , 824, , 825, , 826, , 827, , 828, , 829, , 830, , 831, , 832, , 833, , 834, , 835, , 836, , 837, , 838, , 839, , 840, , 841, , 842, , 843, , 844, , 845, , 846, , 847, , 848, , 849, , 850, , 851, , 852, , 853, , 854, , 855, , 856, , 857, , 858, , 859, , 860, , 861, , 862, , 863, , 864, 





JRDB3DTraj
data
Traceback (most recent call last):
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 193, in eval_sequence
    raw_data = dataset.get_raw_seq_data(tracker, seq, is_3d)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/datasets/_base_dataset.py", line 92, in get_raw_seq_data
    raw_gt_data = self._load_raw_file(tracker, seq, is_gt=True)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/datasets/jrdb_3d_traj.py", line 188, in _load_raw_file
    raise TrackEvalException(
trackeval.utils.TrackEvalException: Ground-truth data contains the following invalid timesteps in seq 0003: 1604, , 1605, , 1606, , 1607, , 1608, , 1609, , 1610, , 1611, , 1612, , 1613, , 1614, , 1615, , 1616, , 1617, , 1618, , 1619, , 1620, , 1621, , 1622, , 1623, , 1624, , 1625, , 1626, , 1627, , 1628, , 1629, , 1630, , 1631, , 1632, , 1633, , 1634, , 1635, , 1636, , 1637, , 1638, , 1639, , 1640, , 1641, , 1642, , 1643, , 1644, , 1645, , 1646, , 1647, , 1648, , 1649, , 1650, , 1651, , 1652, , 1653, , 1654, , 1655, , 1656, , 1657, , 1658, , 1659, , 1660, , 1661, , 1662, , 1663, , 1664, , 1665, , 1666, , 1667, , 1668, , 1669, , 1670, , 1671, , 1672, , 1673, , 1674, , 1675, , 1676, , 1677, , 1678, , 1679, 





JRDB3DTraj
data
Traceback (most recent call last):
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 193, in eval_sequence
    raw_data = dataset.get_raw_seq_data(tracker, seq, is_3d)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/datasets/_base_dataset.py", line 92, in get_raw_seq_data
    raw_gt_data = self._load_raw_file(tracker, seq, is_gt=True)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/datasets/jrdb_3d_traj.py", line 188, in _load_raw_file
    raise TrackEvalException(
trackeval.utils.TrackEvalException: Ground-truth data contains the following invalid timesteps in seq 0004: 1222, , 1223, , 1224, , 1225, , 1226, , 1227, , 1228, , 1229, , 1230, , 1231, , 1232, , 1233, , 1234, , 1235, , 1236, , 1237, , 1238, , 1239, , 1240, , 1241, , 1242, , 1243, , 1244, , 1245, , 1246, , 1247, , 1248, , 1249, , 1250, , 1251, , 1252, , 1253, , 1254, , 1255, , 1256, , 1257, , 1258, , 1259, , 1260, , 1261, , 1262, , 1263, , 1264, , 1265, , 1266, , 1267, , 1268, , 1269, , 1270, , 1271, , 1272, , 1273, , 1274, , 1275, , 1276, , 1277, , 1278, , 1279, , 1280, , 1281, , 1282, , 1283, , 1284, , 1285, , 1286, , 1287, , 1288, , 1289, , 1290, , 1291, , 1292, , 1293, , 1294, , 1295, , 1296, , 1297, 





JRDB3DTraj
data
Traceback (most recent call last):
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 193, in eval_sequence
    raw_data = dataset.get_raw_seq_data(tracker, seq, is_3d)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/datasets/_base_dataset.py", line 92, in get_raw_seq_data
    raw_gt_data = self._load_raw_file(tracker, seq, is_gt=True)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/datasets/jrdb_3d_traj.py", line 188, in _load_raw_file
    raise TrackEvalException(
trackeval.utils.TrackEvalException: Ground-truth data contains the following invalid timesteps in seq 0005: 638, , 639, , 640, , 641, , 642, , 643, , 644, , 645, , 646, , 647, , 648, , 649, , 650, , 651, , 652, , 653, , 654, , 655, , 656, , 657, , 658, , 659, , 660, , 661, , 662, , 663, , 664, , 665, , 666, , 667, , 668, , 669, , 670, , 671, , 672, , 673, , 674, , 675, , 676, , 677, , 678, , 679, , 680, , 681, , 682, , 683, , 684, , 685, , 686, , 687, , 688, , 689, , 690, , 691, , 692, , 693, , 694, , 695, , 696, , 697, , 698, , 699, , 700, , 701, , 702, , 703, , 704, , 705, , 706, , 707, , 708, , 709, , 710, , 711, , 712, , 713, 





JRDB3DTraj
data
Traceback (most recent call last):
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 199, in eval_sequence
    seq_res[cls][met_name] = metric.eval_sequence(data)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/metrics/ospa.py", line 37, in eval_sequence
    dist_t[gt_ids_t[:, None], tracker_ids_t] = min(dist,c) # cut_off distance
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()





JRDB3DTraj
data
Traceback (most recent call last):
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 199, in eval_sequence
    seq_res[cls][met_name] = metric.eval_sequence(data)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/metrics/ospa.py", line 37, in eval_sequence
    dist_c = [min(i,c) for i in dist] # cut_off distance
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/metrics/ospa.py", line 37, in <listcomp>
    dist_c = [min(i,c) for i in dist] # cut_off distance
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()





JRDB3DTraj
data
Traceback (most recent call last):
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 199, in eval_sequence
    seq_res[cls][met_name] = metric.eval_sequence(data)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/metrics/ospa.py", line 37, in eval_sequence
    dist_c = np.minimum(dist,c) # cut_off distance
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/metrics/ospa.py", line 37, in <listcomp>
    dist_c = np.minimum(dist,c) # cut_off distance
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()





JRDB3DTraj
data
Traceback (most recent call last):
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 193, in eval_sequence
    raw_data = dataset.get_raw_seq_data(tracker, seq, is_3d)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/datasets/_base_dataset.py", line 102, in get_raw_seq_data
    ious = self._calculate_similarities(gt_dets_t, tracker_dets_t)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/datasets/jrdb_3d_traj.py", line 406, in _calculate_similarities
    raise NotImplementedError
NotImplementedError





JRDB3DTraj
data
Traceback (most recent call last):
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 193, in eval_sequence
    raw_data = dataset.get_raw_seq_data(tracker, seq, is_3d)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/datasets/_base_dataset.py", line 102, in get_raw_seq_data
    ious = self._calculate_similarities(gt_dets_t, tracker_dets_t)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/datasets/jrdb_3d_traj.py", line 406, in _calculate_similarities
    raise NotImplementedError
NotImplementedError





JRDB3DTraj
data
Traceback (most recent call last):
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 193, in eval_sequence
    raw_data = dataset.get_raw_seq_data(tracker, seq, is_3d)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/datasets/_base_dataset.py", line 102, in get_raw_seq_data
    ious = self._calculate_similarities(gt_dets_t, tracker_dets_t)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/datasets/jrdb_3d_traj.py", line 406, in _calculate_similarities
    raise NotImplementedError
NotImplementedError





JRDB3DTraj
data
Traceback (most recent call last):
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 193, in eval_sequence
    raw_data = dataset.get_raw_seq_data(tracker, seq, is_3d)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/datasets/_base_dataset.py", line 102, in get_raw_seq_data
    ious = self._calculate_similarities(gt_dets_t, tracker_dets_t)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/datasets/jrdb_3d_traj.py", line 406, in _calculate_similarities
    raise NotImplementedError
NotImplementedError





JRDB3DTraj
data
Traceback (most recent call last):
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 193, in eval_sequence
    raw_data = dataset.get_raw_seq_data(tracker, seq, is_3d)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/datasets/_base_dataset.py", line 102, in get_raw_seq_data
    ious = self._calculate_similarities(gt_dets_t, tracker_dets_t)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/datasets/jrdb_3d_traj.py", line 406, in _calculate_similarities
    raise NotImplementedError
NotImplementedError





JRDB3DTraj
data
Traceback (most recent call last):
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 193, in eval_sequence
    raw_data = dataset.get_raw_seq_data(tracker, seq, is_3d)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/datasets/_base_dataset.py", line 102, in get_raw_seq_data
    ious = self._calculate_similarities(gt_dets_t, tracker_dets_t)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/datasets/jrdb_3d_traj.py", line 406, in _calculate_similarities
    raise NotImplementedError
NotImplementedError





JRDB3DTraj
data
Traceback (most recent call last):
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 193, in eval_sequence
    raw_data = dataset.get_raw_seq_data(tracker, seq, is_3d)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/datasets/_base_dataset.py", line 102, in get_raw_seq_data
    ious = self._calculate_similarities(gt_dets_t, tracker_dets_t)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/datasets/jrdb_3d_traj.py", line 406, in _calculate_similarities
    raise NotImplementedError
NotImplementedError





JRDB3DTraj
data
Traceback (most recent call last):
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 193, in eval_sequence
    raw_data = dataset.get_raw_seq_data(tracker, seq, is_3d)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/datasets/_base_dataset.py", line 102, in get_raw_seq_data
    ious = self._calculate_similarities(gt_dets_t, tracker_dets_t)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/datasets/jrdb_3d_traj.py", line 406, in _calculate_similarities
    raise NotImplementedError
NotImplementedError





JRDB3DTraj
data
Traceback (most recent call last):
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 193, in eval_sequence
    raw_data = dataset.get_raw_seq_data(tracker, seq, is_3d)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/datasets/_base_dataset.py", line 102, in get_raw_seq_data
    ious = self._calculate_similarities(gt_dets_t, tracker_dets_t)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/datasets/jrdb_3d_traj.py", line 403, in _calculate_similarities
    similarity_scores = - self._calculate_traj_distance_3d(gt_dets_t, tracker_dets_t)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/datasets/_base_dataset.py", line 385, in _calculate_traj_distance_3d
    assert hyps.shape[1] == 2
AssertionError





JRDB3DTraj
data
Traceback (most recent call last):
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 197, in eval_sequence
    data = dataset.get_preprocessed_seq_data(raw_data, cls)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/datasets/jrdb_3d_traj.py", line 312, in get_preprocessed_seq_data
    similarity_scores = raw_data['similarity_scores'][t][gt_class_mask, :][:, tracker_class_mask]
TypeError: unhashable type: 'numpy.ndarray'





JRDB3DTraj
data
Traceback (most recent call last):
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 197, in eval_sequence
    data = dataset.get_preprocessed_seq_data(raw_data, cls)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/datasets/jrdb_3d_traj.py", line 312, in get_preprocessed_seq_data
    similarity_scores = raw_data['similarity_scores'][t][gt_class_mask, :][:, tracker_class_mask]
TypeError: unhashable type: 'numpy.ndarray'





JRDB3DTraj
data
Traceback (most recent call last):
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 197, in eval_sequence
    data = dataset.get_preprocessed_seq_data(raw_data, cls)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/datasets/jrdb_3d_traj.py", line 312, in get_preprocessed_seq_data
    similarity_scores = raw_data['similarity_scores']['similarity_scores'][t][gt_class_mask, :][:, tracker_class_mask]
TypeError: list indices must be integers or slices, not str





JRDB3DTraj
data
Traceback (most recent call last):
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 197, in eval_sequence
    data = dataset.get_preprocessed_seq_data(raw_data, cls)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/datasets/jrdb_3d_traj.py", line 370, in get_preprocessed_seq_data
    data['similarity_fde_scores'][t] = similarity_fde_scores[gt_to_keep_mask]
KeyError: 'similarity_fde_scores'





JRDB3DTraj
data
Traceback (most recent call last):
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 197, in eval_sequence
    data = dataset.get_preprocessed_seq_data(raw_data, cls)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/datasets/jrdb_3d_traj.py", line 313, in get_preprocessed_seq_data
    similarity_fde_scores = raw_data['similarity_fde_scores'][t][gt_class_mask, :][:, tracker_class_mask]
IndexError: invalid index to scalar variable.





JRDB3DTraj
data
Traceback (most recent call last):
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 197, in eval_sequence
    data = dataset.get_preprocessed_seq_data(raw_data, cls)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/datasets/jrdb_3d_traj.py", line 313, in get_preprocessed_seq_data
    similarity_fde_scores = raw_data['similarity_fde_scores'][gt_class_mask, :][:, tracker_class_mask]
TypeError: list indices must be integers or slices, not tuple





JRDB3DTraj
data
Traceback (most recent call last):
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 199, in eval_sequence
    seq_res[cls][met_name] = metric.eval_sequence(data)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/metrics/de.py", line 54, in eval_sequence
    fde = np.linalg.norm(data['gt_dets_3d'][-1][match_rows]-data['tracker_dets_3d'][-1][match_cols])
IndexError: index 19 is out of bounds for axis 0 with size 19





JRDB3DTraj
data
Traceback (most recent call last):
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 199, in eval_sequence
    seq_res[cls][met_name] = metric.eval_sequence(data)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/metrics/de.py", line 54, in eval_sequence
    fde = np.linalg.norm(data['gt_dets_3d'][-1][match_rows]-data['tracker_dets_3d'][-1][match_cols])
IndexError: index 19 is out of bounds for axis 0 with size 19





JRDB3DTraj
data
Traceback (most recent call last):
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 199, in eval_sequence
    seq_res[cls][met_name] = metric.eval_sequence(data)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/metrics/de.py", line 73, in eval_sequence
    fde = np.linalg.norm(data['gt_dets_3d'][-1][match_rows]-data['tracker_dets_3d'][-1][match_cols])
IndexError: index 5 is out of bounds for axis 0 with size 5





JRDB3DTraj
data
Traceback (most recent call last):
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 199, in eval_sequence
    seq_res[cls][met_name] = metric.eval_sequence(data)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/metrics/de.py", line 73, in eval_sequence
    fde = np.linalg.norm(data['gt_dets_3d'][min_time][match_rows]-data['tracker_dets_3d'][min_time][match_cols])
IndexError: list index out of range





JRDB3DTraj
data
Traceback (most recent call last):
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 199, in eval_sequence
    seq_res[cls][met_name] = metric.eval_sequence(data)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/metrics/de.py", line 48, in eval_sequence
    match_rows, match_cols = linear_sum_assignment(trk_dist)
ValueError: cost matrix is infeasible





JRDB3DTraj
data
Traceback (most recent call last):
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 199, in eval_sequence
    seq_res[cls][met_name] = metric.eval_sequence(data)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/metrics/de.py", line 48, in eval_sequence
    match_rows, match_cols = linear_sum_assignment(trk_dist)
ValueError: cost matrix is infeasible





JRDB3DTraj
data
Traceback (most recent call last):
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 199, in eval_sequence
    seq_res[cls][met_name] = metric.eval_sequence(data)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/metrics/de.py", line 46, in eval_sequence
    dist_sum += dist
ValueError: operands could not be broadcast together with shapes (20,4) (18,4) (20,4) 





JRDB3DTraj
data
Traceback (most recent call last):
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 199, in eval_sequence
    seq_res[cls][met_name] = metric.eval_sequence(data)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/metrics/de.py", line 46, in eval_sequence
    dist_sum += dist
ValueError: operands could not be broadcast together with shapes (20,4) (18,4) (20,4) 





JRDB3DTraj
data
Traceback (most recent call last):
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 199, in eval_sequence
    seq_res[cls][met_name] = metric.eval_sequence(data)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/metrics/de.py", line 46, in eval_sequence
    dist_sum += dist
ValueError: operands could not be broadcast together with shapes (20,4) (18,4) (20,4) 





JRDB3DTraj
data
Traceback (most recent call last):
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 199, in eval_sequence
    seq_res[cls][met_name] = metric.eval_sequence(data)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/metrics/de.py", line 46, in eval_sequence
    dist_sum += dist
ValueError: operands could not be broadcast together with shapes (20,4) (18,4) (20,4) 





JRDB3DTraj
data
Traceback (most recent call last):
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 199, in eval_sequence
    seq_res[cls][met_name] = metric.eval_sequence(data)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/metrics/de.py", line 46, in eval_sequence
    dist_sum += dist
ValueError: operands could not be broadcast together with shapes (20,4) (18,4) (20,4) 





JRDB3DTraj
data
Traceback (most recent call last):
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 199, in eval_sequence
    seq_res[cls][met_name] = metric.eval_sequence(data)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/metrics/de.py", line 46, in eval_sequence
    dist_sum += dist
ValueError: operands could not be broadcast together with shapes (20,4) (18,4) (20,4) 





JRDB3DTraj
data
Traceback (most recent call last):
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 199, in eval_sequence
    seq_res[cls][met_name] = metric.eval_sequence(data)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/metrics/de.py", line 46, in eval_sequence
    dist_sum += dist
ValueError: operands could not be broadcast together with shapes (20,4) (18,4) (20,4) 





JRDB3DTraj
data
Traceback (most recent call last):
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 199, in eval_sequence
    seq_res[cls][met_name] = metric.eval_sequence(data)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/metrics/de.py", line 46, in eval_sequence
    dist_sum += dist
ValueError: operands could not be broadcast together with shapes (20,4) (18,4) (20,4) 





JRDB3DTraj
data
Traceback (most recent call last):
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/eval.py", line 199, in eval_sequence
    seq_res[cls][met_name] = metric.eval_sequence(data)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/saeed/jrdb_toolkit/traj_eval/trajtrack/trackeval/metrics/de.py", line 52, in eval_sequence
    trk_dist = dist_sum / (t1+1+t2+1)
UnboundLocalError: local variable 't2' referenced before assignment





